import './globals.css';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import { Toaster } from 'react-hot-toast';
import SessionProvider from '@/components/SessionProvider';
import { Navbar, Footer } from '@/components';
import type { AppProps } from 'next/app';
import { getServerSession, type Session } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bill-Bot-Baggins',
  description: 'Generated by PTRI11 Pantless Thundergeese',
};

export default async function RootLayout({
  children,
  Session,
}: {
  children: React.ReactNode;
  Session: any;
}) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={Session}>
          <Theme
            appearance='dark'
            accentColor='iris'
            grayColor='sand'
            panelBackground='solid'
            radius='full'
            scaling='90%'
          >
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
