import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/app/AuthProvider';
import  { Navbar, Footer } from '@/components';
import type { AppProps } from "next/app"
import type { Session } from "next-auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bill-Bot-Baggins',
  description: 'Generated by PTRI11 Pantless Thundergeese',
}

export default function RootLayout({
  children,
  Session
}: {
  children: React.ReactNode;
  Session: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider session={Session}>
      <Theme appearance="dark" accentColor="iris" grayColor="sand" panelBackground="solid" radius="full" scaling="90%">
        <Navbar/>
          {children}
          <Footer/>
          <Toaster/>
        </Theme>
        </AuthProvider>
      </body>
    </html>

  )
}
