import '@/app/globals.css';

import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PayStream',
  description: 'Generated by PLTG',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <head>
          <link rel='icon' href='/favicon.ico' />
        </head>
        <body className={`${font.className} dark h-screen`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
